baseURL = 'https://blog.colawithsauce.cn/'
languageCode = 'zh-cn'
title = 'Cola-With-Sauce'
theme = 'PaperMod'

[imaging]
  bgColor = '#ffffff'

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
identifier = "CATEGORIES"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "TAGS"
name = "tags"
url = "/tags/"
weight = 20
