baseURL = 'https://blog.colawithsauce.cn/'
languageCode = 'zh-cn'
title = 'Cola-With-Sauce'
theme = 'PaperMod'

[imaging]
  bgColor = '#ffffff'

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
identifier = "CATEGORIES"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "TAGS"
name = "tags"
url = "/tags/"
weight = 20

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "Hi! I'm colawithsauce, majored in Computer Science, pursuing my Master's degree now. You can find posts about Emacs, HPC, CPP, Philosophy, and other articles"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/cola_vs_sauce"

[[params.socialIcons]]
name = "github"
url = "https://github.com/colawithsauce"
