#+title: All Posts

* DONE 为什么 2023 年，我的“获得感”不够？ :reflection:@article:
:PROPERTIES:
:EXPORT_FILE_NAME: 2023-why-not-enough-sense-of-gain
:END:
今天，2024我反思我2023年，我没有获得感的原因：
1. 输出强度不够：我应该早些地将我的博客重新使用起来，把日常的学习积累分享出来。达到费曼学习法的要求。
2. 太容易分心：关于这个观点，我最近有一个想法，就是使用冥想法。但是把冥想中所有的“呼吸”，换成我欲有所事功的事，这样练习专注的时候也不会觉得是一种“花时间”。
3. 不会悬搁判断：
   - 首先，第一个意义上：这是同冥想“配套”的，不要急于否定自己，觉得自己的努力不可能有结果。
   - 第二个意义上：我应该更加 Open Minded，多看多学，不要因为觉得没用（这种情况占一大部分），或者觉得太难（占另外很大一部分）而完全拒绝相关的知识进入脑海，人为地给自己设置了“心障”。
4. Burn-out：我后面停下来了，这点我承认我对于觉得做了也没有意义的事情就会完全没有动力去做。但是我的目标是“一步登天”，所以作为一个初学者的我，什么样的事情也是会“做了也没有意义”的。因此我觉得我应该去培养一种“珍视”的能力，一种为自己每日的进步而“感到愉悦”的能力。
* DONE Extern C 的用法 :@CPP:
CLOSED: [2024-01-18 Thu 14:00]
:PROPERTIES:
:EXPORT_FILE_NAME: extern_c_usage
:END:
** 原理
extern C 作用的域内，全部的函数与变量名都被编译成 C 的 ABI 格式。因此想要理解 extern C 只需要理解编译器与链接器的行为就好了。
** C++ 使用 C 函数
因为如果我们直接 ~#include~ C 的头文件，如果是在 C 提供了 .c 的源代码的情况下，我们当然可以（大概是大部分时候吧）不用加 extern C，因为我们将使用 C++ 的方式来解释它们，而 C++ 是兼容 C 的。

但是如果我们只有头文件而没有源文件，即 C 代码是用共享库之类的方式给予我们的，我们就需要使用 extern C 来让 C++ 编译器在处理这些函数名的时候不要把它们处理成 C++ 的函数签名形式，而是 C 语言的函数签名模式。若非如此，代码将无法链接，提示无法找到 ~__Zz_testfunc_int_int_~ 之类的有非常奇怪名字的函数。
** C 使用 C++ 函数
我们同样要将 C++ 想要暴露给 C 的接口使用 extern C 修饰，或者直接将这些接口在 ~.h~ 文件里面用 ~extern "C" { ... }~ 括起来。这样，C 就可以调用 C++ 的函数了。
** 其它问题
*** 在C++代码中，在使用 extern C 修饰的函数中，我能否使用 C++ 函数？
这个问题是我作这番研究的原因，而研究完 extern C 的用法后，就应该明白，我们当然可以使用 C++ 函数。因为 extern C 只是告诉编译器要将这个函数名在编译目标文件时不要转换成 C++ 的函数签名，而是使用原名即 C 语言的函数签名形式。而接口是不影响实现要怎么样的。
