:PROPERTIES:
:ID:       21b323e2-ec6f-4ba4-8026-d3ed4a47c2e7
:END:
#+title: 存在与时间
#+hugo_custom_front_matter: :mathjax false
#+hugo_tags: Existentialism
#+hugo_categories: Philosophy
#+DATE: [2024-01-20 Sat 15:42]

* 阅读日志
** 2024-01-17
*** 现象，现相与假象的区别是什么？
根据 https://zhuanlan.zhihu.com/p/27888569 这篇专栏里面对这个问题的解释，现象是指事物显现自身，而现相则是指对于自在之物（不显现的事物）的显现，假象则是对于显现的事物的显现。

引其中一段，可能讲得比较明白：
#+begin_quote
首先是现象：就其自身显示自身者，但这时现象并没有作为现象来把握，因为我们认为现象是对某个不显现的东西是显现，我们理解为现相。在现相中，不存在虚假的东西，只存在单纯显现的东西与单纯不显现的东西。但是那个单纯不显现的东西其实并不真的不显现，只是不被那个显现它的东西按其所是的样子显现出来而已，因而是假象。也就是说：假象之所以是现象，又是对现象的遮蔽，是因为，它确实显现了，但不是如其自身来显现，而是以歪曲了的方式对已经显现者的二度显现，并且理解把另一个显现者理解为不显现者。
#+end_quote

所以说，不存在现相？因为一切事物都会显现自身，一切都是现象？

这个问题我想可以再次引用：
#+begin_quote
严格来讲只存在两种情况：1.现象，指的是对象的自身显现，此在与它的世界的源始关系。2.现相，指某种不显现的东西的显现，此在与他的世界的隔绝，在此此在孤立于世界。但是，现象是存在上的实情，而非存在论上的实情。而现相是存在上的虚假事件，根本不存在现相这样的东西，但它是一种存在论的建构。

假象是一种存在上的实情，也是一种存在论上的建构。因为假象的形式结构是现相：对某种不显现的东西的显现。但它也是实情：因为被显现的东西本身就是一个显现。因此只有假象具体的，是我们所切近接触的东西，而假象既是一种现象，它本质上包含着现象的那种敞开性，又是一种遮蔽，它是对那自身显现者的歪曲，是对它不能是的东西的显现。
#+end_quote
*** 逻各斯概念
其本来意思是『说』，即将某种东西讲出来，把所涉及之事物展示出来（给人看），因此它才可能是真的或是假的。

----

但是这里，海德格尔并没有使用『说的与真实情况相符合』来定义 *真理* 。真理的本来意思是『去除遮蔽』，所以其逻各斯的『真在』说的是，把话题所及的存在者从其掩蔽状态拿出来，让人把它当作无遮蔽的东西看待。也即是 *揭示* 话题所及的存在者。而『假在』，则是在说遮蔽这一意义上的欺骗，把某种东西放到另一种东西前面（让人看），（把它挡住）使得它作为它所不是的样子而呈现出来。
** 2024-01-20
*** 命题
1. 此在的本质在于它的生存
2. 此在的本质属性是它的存在
3. 此在最本己的可能性是其自己的存在
4. 此在本质上总是它的可能性
5. 此在对之有所作为的存在，总总是“我的存在”
*** 推论
**** 此在是存在先于本质的
由于『2. 此在的本质属性是它的存在』，『4. 此在最本己的可能性是其自己的存在』。

此在的存在这一属性是被给予的，而且存在这一「本质属性/可能性」是最本己的，而相对的，其它的可能性与属性则是在这一最本己的「可能性」之后才具有的。所以说此在的存在是先于本质的。
**** 此在是向来我属的
原文中未给出详细推论过程，下面是我的推论过程：
1. 由于『5. 此在对之有所作为的存在，总总是“我的存在”』。此在的『怎样去是』即其存在，只有此在这个存在者的作为才能决定。
2. 故不存在两个同样的『此在』，故此在是向来我属的。

问题：如果说两个存在者的『同属』意指此两个存在者的存在完全相同，则上推论过程成立。但如果说『同属』是指具有相同的一系列的属性，则上述命题是否有问题呢？比如说厨师这个属，它就可以概括两个存在者。是否说如果我们使用什么属去概括此在的时候，我们就是用普通的存在者而非此在的眼光去看他们了？我们不能够用『属』去定义此在？

不过，我还是能够大概理解它的意思。往后看吧
**** 此在选择它的可能性的同时，也在选择自身
因为『4. 此在本质上总是它的可能性』，所以此在选择它的可能性 == 选择此在自身

*** 问题
- 所谓的此在的“我的存在”，是否意指此在这个存在者的存在本身？
  - 是的，在第9节的开头就讲了——“这种存在者的存在总是我的存在”
*** 参考
https://zhuanlan.zhihu.com/p/373641802
** 2024-02-10
*** 海德格尔认为对于存在问题长久以来的三个成见是什么？ :card:
:PROPERTIES:
:ANKI_NOTE_HASH: c95b6e8f86d786cc47d982912e4ba8e5
:ANKI_NOTE_ID: 1707539738356
:END:
1. 存在是最基础的概念，因此也是最空洞的概念， *不需要* 定义
2. 存在无法定义
3. 存在是自明的
*** 为什么说存在不是空洞的概念？ :card:
之前所言的存在是在说存在者，或者言存在性。杯子是存在者，椅子是存在者。而红色则必须是依附于杯子或者椅子才能存在，它不能作为一个实体存在（相对地，椅子可以改变它的颜色而仍然以实体方式存在）。但是我们也可以说红色“存在”，但是红色的存在与杯子的存在它们是不一样的意思。这种情况我们『类比地』使用了这个词，是参照了『存在』这一词语的源始的和无条件的意义使用这个词。中世纪各个哲学家讨论了存在的意义问题，但是并没有讨论清楚。

而正因为海德格尔认为之前所言的存在论都是在讲『存在者』，都没有真正言及『存在』，因此存在这一概念是最基础的概念，但是却并不是空洞的概念，仍然有讨论的空间。
*** 为什么说存在问题是可以定义的？ :card:
之所以说存在问题是不可定义的，是因为之前都是以属加种差定义法来定义问题。但是存在它是最抽象的概念，因此它之上是没有属了，因此就无法定义。但是海德格尔认为种加属差定义法只『适用于存在者』，但『不适用于存在』。

*** 为什么说存在并不是自明而无法讨论的？
** 2024-02-18
我们何以观察一个事物？首先指出，认识是此在在世的一种样式。

这里海德格尔提出了一个可能的反论：世界原本得在主体的超越活动中才能达到，今若预设认识已经依于它的世界而存在，那还有什么问的呢？这句问话我没有弄明白，我想可能是在说世界本来是主体所不认识的，需要主体超越自己而去追问它，它才能被主体所认识。而这里颠倒之后，就让我们的认识活动没有意义了，因为已经没有什么需要追问了？这样解也很奇怪，因为这里只讲了认识的存在依于世界，但是在这个结构下，认识仍然可以去追问世界呀。这段话我是不明白的。

前面说，在世是一种操劳活动。而此在要对（“世界中的”？）某现成事物有所认识，就需要我们对世界的操劳有所『残断』。此在『从一切制作、操作等等抽手不干之际，操劳便置身于现在还仅剩的“在之中”的样式中，即置身于“还仅仅延留在某种东西处”这种情况中。』（这句话的意思也许是说，当此在认识某现成事物，就会从其它的操劳中离开？）『而只有基于这种向着世界的存在方式，并且作为这种存在方式的一种样式，才可能以明确的形式“观察”如此这般照面的存在者』

在观察某现成事物时，此在的观望自行进入一种独立持留于世界内的存在者。这种滞留乃是对所有操作和利用的放弃，在这种滞留中发生对现成东西的 *知觉* 。（也许就是说此在要在一种『全心全意』地『观察』的时候，也就是滞留状态中，才能发生知觉。）

被知觉的东西和被规定的东西可以在语句中被说出，于是作为这样被道出的东西保持和保存下来。

下面又说：这种知觉，不是『过程』，而是一种在世的样式。

#+begin_quote
把捉某事物的时候，不是认识从主体的『囚笼』中出去，而是认识早已『滞留』于世界中与其照面的存在者。
#+end_quote

* Questions
** 第一章里面，所说的『存在论』是指的什么？
** 此在的生存就是一种存在，那么生存论与存在论之间有何关联？
